### ISSUE TITLE
error: 'MBSTRING' does not name a type

### ISSUE THREAD

**Issue by zainurihasan** [mobizt/ESPForm#2]
i try the example but it giveme an error "error: 'MBSTRING' does not name a type", how i can fixit?

**Comment by mobizt** [comment]
The error you mentioned is not complete error and it should not happen.

There are compilation errors that can be the root cause of above error due to the including files error from third parties libraries that have been installed which they also existed in the ESP8266/ESP32 Arduino core libraries too e.g. "SD.h" and  this library depends on it.

If you installed "SD.h" library in libraries folder, remove it.

Then update the library and try again.

**Comment by mobizt** [comment]
I have found the issue in library publishing.

Please update the library and try again.
